# Generated by Django 5.0.7 on 2024-09-03 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletterapp', '0002_newsletter_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время начала')),
                ('periodicity', models.CharField(blank=True, max_length=20, null=True, verbose_name='Периодичность отправки')),
                ('status', models.BooleanField(default=False, verbose_name='Статус')),
                ('newsletter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='newsletterapp.newsletter')),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
