# Generated by Django 5.0.7 on 2024-09-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletterapp', '0004_remove_newslettersettings_start_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettersettings',
            name='periodicity',
            field=models.IntegerField(default=0, verbose_name='Периодичность отправки в днях'),
        ),
        migrations.AlterField(
            model_name='newslettersettings',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала'),
        ),
    ]
