# Generated by Django 5.0.7 on 2024-09-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletterapp', '0005_alter_newslettersettings_periodicity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersettings',
            name='send_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время отправки'),
        ),
    ]
