# Generated by Django 5.0.7 on 2024-09-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletterapp', '0007_newslettersettings_next_send_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newslettersettings',
            name='start_date',
        ),
        migrations.AddField(
            model_name='newslettersettings',
            name='last_send_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата последней отправки'),
        ),
        migrations.AlterField(
            model_name='newslettersettings',
            name='next_send_day',
            field=models.DateField(blank=True, null=True, verbose_name='Дата ближайшей отправки'),
        ),
        migrations.AlterField(
            model_name='newslettersettings',
            name='periodicity',
            field=models.PositiveIntegerField(default=0, verbose_name='Периодичность отправки в днях'),
        ),
    ]
