# Generated by Django 5.0.7 on 2024-09-05 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletterapp', '0008_remove_newslettersettings_start_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_date', models.DateField(blank=True, null=True, verbose_name='Дата отправки')),
                ('send_time', models.TimeField(blank=True, null=True, verbose_name='Время отправки')),
                ('status', models.BooleanField(verbose_name='Статус')),
                ('server_answer', models.TextField(verbose_name='Ответ почтового сервера')),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletterapp.newsletter')),
            ],
            options={
                'verbose_name': 'Отправка',
                'verbose_name_plural': 'История отправок',
            },
        ),
    ]
