# Generated by Django 5.0.7 on 2024-09-05 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletterapp', '0009_newsletterlogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletterlogs',
            name='newsletter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='newsletterapp.newsletter'),
        ),
        migrations.AlterField(
            model_name='newsletterlogs',
            name='server_answer',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ почтового сервера'),
        ),
    ]
