# Generated by Django 5.0.7 on 2024-09-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletterapp', '0010_alter_newsletterlogs_newsletter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletterlogs',
            name='send_method',
            field=models.CharField(default='По расписанию', max_length=15, verbose_name='Способ отправки'),
        ),
        migrations.AlterField(
            model_name='newsletterlogs',
            name='send_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата отправки'),
        ),
        migrations.AlterField(
            model_name='newsletterlogs',
            name='send_time',
            field=models.TimeField(auto_now_add=True, null=True, verbose_name='Время отправки'),
        ),
    ]
