# Generated by Django 5.0.7 on 2024-09-22 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_users_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'permissions': [('can_view_users', 'view_users_list'), ('can_block_user', 'block or unblock user')], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
