# Generated by Django 5.0.7 on 2024-09-26 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_users_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'permissions': [('can_view_users', 'view users list'), ('can_block_user', 'block or unblock user'), ('can_publish_post', 'can change published sign')], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
