# Generated by Django 5.0.7 on 2024-09-26 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_users_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'permissions': [('can_view_users', 'view users list'), ('can_block_user', 'block or unblock user')], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
