# Generated by Django 5.0.7 on 2024-09-25 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_created_at_blogpost_likes_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='published_sign',
            field=models.CharField(choices=[(True, 'Опубликовано'), (False, 'Не опубликовано'), ('Work', 'На проверке менеджера')], default=False, verbose_name='Знак публикации'),
        ),
    ]
