# Generated by Django 5.0.7 on 2024-09-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogpost_published_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='published_sign',
            field=models.CharField(choices=[('pub', 'Опубликовано'), ('no_pub', 'Не опубликовано'), ('work', 'На проверке менеджера')], default=False, verbose_name='Знак публикации'),
        ),
    ]
