# Generated by Django 5.0.7 on 2024-09-26 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogpost_published_sign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='likes_count',
        ),
    ]
