# Generated by Django 5.0.7 on 2024-09-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blogpost_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='blog_image/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='published_sign',
            field=models.CharField(choices=[('pub', 'Опубликовано'), ('no_pub', 'Не опубликовано'), ('work', 'На проверке менеджера')], default='no_pub', verbose_name='Знак публикации'),
        ),
    ]
